### PR TITLE
testing

### PR DESCRIPTION
**Pull request by danielpinto8zz6**

### CODE REVIEW

**Comment by Anti-Li** [comment]
One more commit please

**Comment by danielpinto8zz6** [comment]
done

**Comment by Anti-Li** [comment]
Okay, only one commit.
image
The owner rebase, but not contributor.

**Comment by danielpinto8zz6** [comment]
well, the owner can do, but there will be a lot of commits named "merge..." wich is irrelevant, and can be avoided if the code is clean when pull request

**Comment by Anti-Li** [comment]
But there's option "Squash and merge". Look the description below.

**Comment by danielpinto8zz6** [comment]
yes

**Comment by Anti-Li** [comment]
You can try to create a PR again. :smiley:

**Comment by danielpinto8zz6** [comment]
So, I can't merge your pr on my code now, because there are a lot of conflicts atm, plus the relevant part is already picked, just make sure you rebase your repo to look like mine before make changes

**Comment by Anti-Li** [comment]
Okay. You are right, I know less about Git.

https://git-scm.com/book/en/v2/Git-Branching-Rebasing
https://www.git-tower.com/learn/git/ebook/cn/command-line/advanced-topics/rebase

They said merge and rebase are two different way but both can integrate changes from one branch into another. 

> Rebase vs. Merge
Now that you’ve seen rebasing and merging in action, you may be wondering which one is better. Before we can answer this, let’s step back a bit and talk about what history means.

One point of view on this is that your repository’s commit history is a record of what actually happened. It’s a historical document, valuable in its own right, and shouldn’t be tampered with. From this angle, changing the commit history is almost blasphemous; you’re lying about what actually transpired. So what if there was a messy series of merge commits? That’s how it happened, and the repository should preserve that for posterity.

The opposing point of view is that the commit history is the story of how your project was made. You wouldn’t publish the first draft of a book, and the manual for how to maintain your software deserves careful editing. This is the camp that uses tools like rebase and filter-branch to tell the story in the way that’s best for future readers.

Thank you. I know the new way to integrate changes from one branch into another now.

**Pull request merged**
